### ISSUE TITLE
How to generate the cffi.cdef strings?

### ISSUE THREAD

**Issue by Tenari** [Pyrolistical/zig-cffi-python#1]
aside from manually translating, I assume zig has some facility for automatically creating these cdefs?

also thanks for the help putting these examples together.

**Comment by Pyrolistical** [comment]
You need to manually write them. cffi allows python to call into a c lib, it has nothing to do with zig. We just happen to be generating a c lib with zig.

See https://cffi.readthedocs.io/en/latest/ref.html
